---
name: docker_build_push
on:
    push:
jobs:
    build_n_push:
        runs-on: ubuntu-latest
        steps:
            - uses: docker/login-action@v3
              with:
                username: xycainoff
                password: ${{ secrets.XYCAINOFF_DOCKER_HUB }}
            - uses: docker/setup-qemu-action@v3
            - uses: docker/setup-buildx-action@v3
            - uses: docker/build-push-action@v6
              with:
                platforms: linux/amd64,linux/arm64
                push: true
                tags: user/app:latest
