---
name: docker_build_push
on:
  push:
jobs:
  build_n_push_app:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.USERNAME }}
          password: ${{ secrets.XYCAINOFF_DOCKER_HUB }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.USERNAME }}/hexlet_app:latest
  build_n_push_caddy:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.USERNAME }}
          password: ${{ secrets.XYCAINOFF_DOCKER_HUB }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: services/caddy/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.USERNAME }}/hexlet_rev_proxy:latest
